### ISSUE TITLE
Detail more better a topic

### ISSUE THREAD

**Issue by ACSantos47** [NetAppDocs/ontap-systems-upgrade#106]
### Page URL

https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-considerations.html

### Page title

Considerations for upgrading controller hardware

### Summary

Reading this documentation a found the topic below on Requirements and limitations table:

Am I moving internal storage or converting the system to a drive shelf?

1. Verify that the root aggregate size and the number of disks supported by the new system are equal to or greater than those supported by the original system](https://hwu.netapp.com/).
2. Upgrade by moving storage](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-by-moving-storage-parent.html) (a disruptive procedure).

In my situation I´m studying to do a Head Upgrade of FAS2650 to FAS2750. According the topic 1 my destination system have to do equal or more space/disks to root aggregate but FAS2750 needs less space to store root agregate. On this case is possible to do Head Upgrade or not? I want to convert FAS2650 to disk shelf before.
If supported I ask you to modify this part of document to do more clear this cenario.

Thank you.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @ACSantos47, thank you for bringing this to our attention. I'll consult with the hardware upgrades team and update the documentation accordingly. Please let me know if you are you waiting on the documentation updates to proceed with your upgrade?

**Comment by ACSantos47** [comment]
Hi Paula, thank you for your fast response.
Answering your question is yes, I´m waiting for this information to proceed
to Head Upgrade.

Thank you.




Em qui., 8 de fev. de 2024 às 07:23, Paula Carrigan <
***@***.***> escreveu:

**Comment by netapp-pcarriga** [comment]
Thank you, @ACSantos47, for confirming.

**Comment by ACSantos47** [comment]
Hi Paula, I hope you are fine.
Do you have some information about this request?

Regards.




Em qui., 8 de fev. de 2024 às 09:38, Paula Carrigan <
***@***.***> escreveu:

**Comment by netapp-pcarriga** [comment]
Hi @ACSantos47, all is good thanks. 

I was able to get confirmation that you can proceed with performing a head upgrade by converting a FAS2650 to a disk shelf and then upgrading to a FAS2750.
