### ISSUE TITLE
In this table we need to account for the changes in the SP/E0M being consolidated on the A70/A90 (from the A800)

### ISSUE THREAD

**Issue by ericd-netapp** [NetAppDocs/ontap-systems-upgrade#110]
### Page URL

https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/cable-node1-for-shared-cluster-HA-storage.html

### Page title

Cable node1 for shared cluster-HA and storage (AFF A800 upgrade only)

### Summary

The A800 has 2 distinct separate ports for management, (e0M and BMC).  On the A70/A90, these 2 physical ports are put together into 1 port.  People doing this transition need to account for 2 physical cables doing into 1 and to be sure they are going to the same switch and/or on the same subnet.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by andris-ntap** [comment]
AFF A800 Mgmt. ports:
![image](https://github.com/NetAppDocs/ontap-systems-upgrade/assets/84108159/cfde0689-e3a3-41ab-b780-55fac6fd8fce)

AFF A90 Mgmt. ports:
![image](https://github.com/NetAppDocs/ontap-systems-upgrade/assets/84108159/4c8fc49a-d523-4be7-ad70-5dd69ee7a475)

**Comment by netapp-pcarriga** [comment]
Hi @ericd-netapp, thanks for bringing this to our attention. I've opened AFFASDOC-240 to track this request internally and added you as a watcher.

**Comment by netapp-pcarriga** [comment]
@ericd-netapp Hi Eric, I have added an additional table with information about how to connect the e0M and BMC ports. I hope this makes the task clear.
