### ISSUE TITLE
Errant text in the CLI output

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems-upgrade#113]
### Page URL

https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-restore-root-volume-config.html

### Page title

Restore the root volume configuration

### Summary

You have some errant text in the CLI output here:

Selection (1-9)? 6
**Controller Hardware Upgrade Express Guide 19    <<<<<<<
Upgrading controller hardware by moving storage <<<<<<**
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: y

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thanks @andris-ntap. I'll update you here when this is corrected.

**Comment by netapp-pcarriga** [comment]
Thank you @andris-ntap. The errant text has been removed: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-restore-root-volume-config.html
