### ISSUE TITLE
"two onboard disks" looks to be incorrect text

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems-upgrade#116]
### Page URL

https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html

### Page title

Decide whether to use the aggregate relocation procedure

### Summary

This sentence: The AFF A70 and AFF A90 are integrated systems with two onboard disks and two controllers in a single chassis.

... mentions "two onboard disks".

This text is likely incorrect. 
Is it referring to the two rows of 24 internal drive bays (48 total drive bays) in the front of the chassis, perhaps?
Reach out to me offline to discuss the correct intent.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thanks @andris-ntap. I'll investigate and update the documentation.

**Comment by netapp-pcarriga** [comment]
Hi @andris-ntap, we've published the following change:
"The AFF A70 and AFF A90 are integrated systems with two controllers in an HA configuration and onboard disks in a single chassis."
