### ISSUE TITLE
FAS2620 upgrade also possible with later versions than 9.11.1P7?

### ISSUE THREAD

**Issue by pdiddens** [NetAppDocs/ontap-systems-upgrade#118]
### Page URL

https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/index.html

### Page title

Overview

### Summary

Please clarify whether 9.11.1P7 is required on FAS2620 for the controller upgrade or whether later patch-releases also work.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thank you @pdiddens. I'll investigate and update you here.

**Comment by netapp-pcarriga** [comment]
@pdiddens, we've clarified in the documentation that FAS2620 supports ONTAP 9.77.1P7 and later patch releases:
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/index.html
Thank you for helping us improved our customer documentation.
