### ISSUE TITLE
Command for reassigning node1's disks is wrong

### ISSUE THREAD

**Issue by tomdewit** [NetAppDocs/ontap-systems-upgrade#12]
Page: [Attach storage shelves and reassign disk ownership](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-attach-shelves-reassign-disks.html)

Chapter 'Attach storage shelves and reassign disk ownership'
In Step 4 the command; disk reassign -s node1_sysid -d node3_sysid -p node2_sysID is wrong and must be:
disk reassign -s node1_sysid -d node3_sysid -p node4_sysID

**Comment by netapp-martyh** [comment]
Thanks, Tom, for the feedback. We will confirm your comment and update the docs.

**Comment by netapp-pcarriga** [comment]
Hi Tom,
BURT 1441731 was created to review your feedback with a product engineer.
I can confirm that "disk reassign -s node1_sysid -d node3_sysid -p node2_sysID" is the correct command.
Thanks again for your feedback.
Paula

**Comment by netapp-pcarriga** [comment]
Hi Tom,
I created BURT 1441731 to have your review feedback reviewed by a product engineer.
I can confirm that "disk reassign -s node1_sysid -d node3_sysid -p node2_sysID" is the correct command.
If you try to run "disk reassign -s node1_sysid -d node3_sysid -p node4_sysID", it will report an error.
Thanks again for your feedback.
