### ISSUE TITLE
Add card for: Use "system controller replace" commands to upgrade AFF A700 to AFF A900 running ONTAP 9.10.1 RC2 or later

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap-systems-upgrade#18]
Page: [AFF and FAS System Upgrade Documentation](https://docs.netapp.com/us-en/ontap-systems-upgrade/index.html)

currently have the 9.8 card but not for the new 9.10.1 A700 to A900 in-chassis conversion upgrade

**add new card :** 

**Use "system controller replace" commands to upgrade AFF A700 to AFF A900 running ONTAP 9.10.1 RC2 or later**

and link to : 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html#

**Comment by netapp-pcarriga** [comment]
@loganbaez Thank you for your feedback. We'll get this update made to the documentation.

**Comment by netapp-pcarriga** [comment]
@loganbaez To help process your request correctly, when you get the chance, could you please provide the following information:
- A doc link or a screen shot containing example text for the change that you are requesting   
- Confirm the location in the [Use "system controller replace" commands to upgrade AFF A700 to AFF A900 running ONTAP 9.10.1 RC2](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/index.html) or later where this update is required.

**Comment by loganbaez** [comment]
Hello Paula,

You can cancel this request.

didn’t realize this was there already

***@***.***

Thank you


Logan Baez
Knowledge Domain Expert (KDE) Prime - HW
Technical Support Center
***@***.******@***.***>
Work hours: Monday-Friday, 7AM to 3:30PM EST (GMT -4)
***@***.***

**Comment by netapp-pcarriga** [comment]
Thank you for letting me know, @loganbaez. 
Closing this request.
