### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by lamandanetapp** [NetAppDocs/ontap-systems-upgrade#21]
Page: [Apply RCF files and recable the switches](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual/apply_RCF_files_recable_switches.html)

The two 'NetApp Downloads' links on this page re-direct to the main support site page, instead of leading to the actual download page as intended. This should be corrected.  Thanks!

The URLs in question:

Steps
Locate the RCF files for your configuration.
You must use the RCF files that match your switch model.
[NetApp Downloads: MetroCluster Configuration Files for Brocade Switches](http://mysupport.netapp.com/NOW/download/software/metrocluster_brocade/sanswitch/index.shtml)
[NetApp Downloads: MetroCluster Configuration Files for Cisco Switches](http://mysupport.netapp.com/NOW/download/software/metrocluster_cisco/sanswitch/index.shtml)

The page I'm viewing:
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual/apply_RCF_files_recable_switches.html

**Comment by netapp-pcarriga** [comment]
@lamandanetapp Thank you for your feedback. We'll get both these links updated in the documentation.

**Comment by netapp-pcarriga** [comment]
@lamandanetapp - We've updated the links for installing the Brocade and Cisco switch RCFs which you can view [here].(https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual/apply_RCF_files_recable_switches.html)
Thanks again for your feedback and helping us improve our customer documentation.
Closing this ticket.
