### ISSUE TITLE
Syntax error in Korean translation

### ISSUE THREAD

**Issue by natsl1** [NetAppDocs/ontap-systems-upgrade#29]
Page: [스토리지를 이동할 때 업그레이드를 준비합니다](https://docs.netapp.com/ko-kr/ontap-systems-upgrade/upgrade/upgrade-prepare-when-moving-storage.html)

Hi Team,

I am not sure this is the way to report such broad syntax errors in the translation system but I was told by the GPSO Globalization team to report by Github. 

Please find the couple of points that I have addressed the issue in translation below and please be advised that these errors are not only applied to the ontap-systems-upgrade but most of the English to Korean translated NetAppDocs. 

If you find this not an appropriate repository to write this issue, please let me know. 

------------------------------------------------------------------------------------------

We believe that these new Korean-translated technical docs will greatly help the partners and customers who are not comfortable with English. 

But we noticed some major errors in the Korean translated technical documents on docs.netapp.com. 

We understand that this is a machine translation and even if we disregard the grammatical translation errors, the following systematic errors made the document difficult to understand in the Korean language.

Please find these 2 documents that I have used for reference.
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-prepare-when-moving-storage.html
https://docs.netapp.com/ko-kr/ontap-systems-upgrade/upgrade/upgrade-prepare-when-moving-storage.html

________________________________________
1. Force Translated Commands
For example, Under step 3, the command in English should not be translated. But some of them have mixed force translated commands. I presume that the commands marked in light font were meant to show that they are the “commands” but most of them were translated into Korean. 
e.g., network interface show -> 네트워크 인터페이스 show, Yes -> 예, which should not happen. 
 
![image](https://user-images.githubusercontent.com/45701294/167359863-d2fefe98-a406-45f1-88da-61fa0b8716f1.png)
![image](https://user-images.githubusercontent.com/45701294/167359895-eb43d4b5-f9dd-44ee-9e57-a3939439b7b7.png)
 
![image](https://user-images.githubusercontent.com/45701294/167359921-17571936-0d93-46f1-ba55-44e1e25291f4.png)
![image](https://user-images.githubusercontent.com/45701294/167359936-e8201bc7-289d-4623-a489-5f7a885a0713.png)

 
________________________________________
2. Grammatical order gets strange when it is mixed up with the hyperlink. 
Under step 5A, the translation feels like it is not considering the blue text for the hyperlink for complete translation. 
 
![image](https://user-images.githubusercontent.com/45701294/167359959-601776f1-f5ea-4362-9574-1a04fe848151.png)
![image](https://user-images.githubusercontent.com/45701294/167359972-db245c10-3ee2-4e89-a37e-59cdc4e72a6c.png)

 
________________________________________
3. Missing the bold and enlarged font for the headings.
If you look at the exported pdf file for documents in docs.netapp.com, You can easily see that the title has a bold and enlarged font compared to the regular body. But in Korean documents, the bold and enlarged font for the heading is missing and it is confusing the reader by not separating the head and body.
 
 
![image](https://user-images.githubusercontent.com/45701294/167360026-857813f8-514d-48ff-890b-ad4a47aa7449.png)
![image](https://user-images.githubusercontent.com/45701294/167360042-08ce8893-ac11-4620-8224-1d1aad10cee6.png)

________________________________________
4. The technological terminologies like HA and Storage Failover should not be translated to Korean.

________________________________________
5. Missing the change line in the command section.
 
![image](https://user-images.githubusercontent.com/45701294/167360059-f8c5e6ef-2526-4ccc-8292-337a83c11c71.png)
![image](https://user-images.githubusercontent.com/45701294/167360067-64670797-dc06-40b2-b2c4-23263fe961b9.png)

We hope some of these points would be considered to improve the translation system to help to understand better for us and the partners. 

Thanks.

**Comment by netapp-gudugunti** [comment]
Thanks! @natsl1 for reporting the issues in Korean translation.
There are some overtranslation issues here along with styling issues in the target language for PDF format.
We shall take up these issues for evaluation and get back to you.

Regards,
Ashwath

**Comment by natsl1** [comment]
Hey everyone, Any update?

**Comment by netapp-gudugunti** [comment]
Hi @natsl1,

My apologies for the delay in response.
We have completed the first round of assessment.
Issues are identified and further investigation is in progress.
Please stay tuned for updates against each reported issue.

Regards,
Ashwath

**Comment by ntap-bmegan** [comment]
@netapp-gudugunti - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @natsl1 - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @jameshom

**Comment by natsl1** [comment]
@ntap-bmegan 
Item 1, 3, and 5 appears to be fixed but 2 and 4 still persist. I guess item 4 is more of a personal preference but 2 isn't.

**Comment by ntap-bmegan** [comment]
Thanks, @natsl1. I'll follow up with the localization team.

**Comment by netapp-gudugunti** [comment]
Hi @natsl1 
Thanks! for your patience.

Regarding item 2:
The topic has since been updated to link to a different location, and the author who made the update moved the link out of the sentence. However, the original hyperlink text (NetApp Support 사이트) seems to have been correct given the English. Can you clarify the problem you saw in the original text?

Regarding item 4:
The linguistic team has reviewed your observations. 
Per the terminology standards, they do not find the translation incorrect.

If you still feel that we could improve the translation, 
please do reopen this ticket and let us know
1.	the issue with the current translated term, and
2.	the alternatives to the existing translation.
