### ISSUE TITLE
Why are we saying encrypted volumes are going OFFLINE - like this is expected behaviour?

### ISSUE THREAD

**Issue by wdiane1** [NetAppDocs/ontap-systems-upgrade#30]
Page: [Restore key-manager configuration on node3](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/restore_key-manager_configuration_node3.html)

**Comment by netapp-pcarriga** [comment]
@wdiane1 Thank you for your feedback!
I'll follow up on this issue and get back to you as soon as possible.

**Comment by netapp-pcarriga** [comment]
@wdiane1 - Information has been added to the "restore key-manager configuration" sections across in the ONTAP systems upgrade documentation on the requirement to restore key-manager to prevent encrypted volumes being taken offline after you relocate by using ARL. Here's an example: [Restore key-manager configuration on node3](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/restore_key-manager_configuration_node3.html)
Closing this comment and thanks again for your feedback!
