### ISSUE TITLE
Restore key-manager configuration on node3

### ISSUE THREAD

**Issue by wdiane1** [NetAppDocs/ontap-systems-upgrade#35]
Page: [Restore key-manager configuration on node3](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/restore_key-manager_configuration_node3.html)

You can reword a bit, the what needs to occur during controller replacement with onboard key manager in ONTAP 9.8 and later is the following:

1.	From UP node, perform “security key-manager onboard show-backup” and confirm have the passphrase
2.	During the 1st controller upgrade with only root aggregate disks assigned and new node is booted up 
3.	New node is up and network is remediated on the new node
4.	Halt the new node 
5.	Go back to the Special Boot – LOADER> boot_ontap menu and recover onboard key manager secrets
Please choose one of the following:
 
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 10
 
              Enter the passphrase for the onboard key manager you obtained at the step 1.
              When prompted to enter the backup data, paste the backup data you captured at the step 1, when asked
              Then when boots back to special boot menu – chose (1) Normal Boot
 
1.	When boots into ONTAP, you must run “security key-manager onboard sync” command from this new node.
2.	Run “security key-manager key query -node <new-node> -fields restored and confirm the SVM-KEK and NSE-AK are restored
3.	Perform the aggregate relocation. Once the aggregate relocation is complete, verify volumes are all online

**Comment by ntap-bmegan** [comment]
@netapp-aoife - Please update status or close if work is complete.

**Comment by netapp-aoife** [comment]
Hi Diane, 

This update is now published: 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/restore_key-manager_configuration_node3.html
