### ISSUE TITLE
Need Step 3 to verify the SVM-KEK key is restored

### ISSUE THREAD

**Issue by wdiane1** [NetAppDocs/ontap-systems-upgrade#36]
Page: [Restore key-manager configuration on node3](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/restore_key-manager_configuration_node3.html)

3. Verify the SVM-KEK key is restored "true" on node3 before ARL the data aggregates in order to prevent outage
::> security key-manager key query -node <node3> -fields restored -key-type SVM-KEK

**Comment by netapp-pcarriga** [comment]
@wdiane1 - Thank you for your feedback.
I'll include this issue in the BURT created for issue #36 as they both relate to the same section in the documentation.

**Comment by ntap-bmegan** [comment]
@netapp-pcarriga - Please update status or close if work is complete.

**Comment by netapp-pcarriga** [comment]
@wdiane1 - This update has been included and is being tracked in GH #35. Closing this issue.
