### ISSUE TITLE
Update to NSE steps

### ISSUE THREAD

**Issue by wdiane1** [NetAppDocs/ontap-systems-upgrade#37]
Page: [Install and boot node3](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/install_boot_node3.html)

27. If NetApp Storage Encryption (NSE) is in use on this configuration, the setenv bootarg.storageencryption.support command must be set to true, and the kmip.init.maxwait variable must be set to off to avoid a boot loop after the node1 configuration is loaded:

setenv bootarg.storageencryption.support true

setenv kmip.init.maxwait off

With kmip.init.maxwait set to off, tells ONTAP to NOT retrieve the authentication keys from the external key manager.
This is a bad idea to turn this feature off.  With this feature turned off the node is booted without any keys and if a power outage occurs with this bootarg set to off and AUTOBOOT is on - then ALL the NSE drives with authentication key will be permanently locked and all data is lost.

Not something to publicly document.  You should say call NetApp Support for encryption specialist to assist.

**Comment by netapp-pcarriga** [comment]
@wdiane1 - Thank you for your feedback. 
I'll have your recommendations verified and then update the documentation.

**Comment by ntap-bmegan** [comment]
@netapp-pcarriga - Please update status or close if work is complete.

**Comment by ntap-bmegan** [comment]
@netapp-pcarriga - What is the status of this issue?

**Comment by netapp-pcarriga** [comment]
@wdiane1 - Thanks again for your feedback, 
This issue has been added to and is being tracked in issue #35. Closing this issue.

**Comment by netapp-pcarriga** [comment]
@wdiane1 Hi Diane, the updates on setting the "bootarg" and "maxwait" variables in Step 27 are now published with additional information on how to determine if your system uses self-encrypting drives and the types self-encrypting of drives support by ONTAP. You can view these updates using the following links:
- [Prepare the nodes for upgrade](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/prepare_nodes_for_upgrade.html#correct-aggregate-ownership-if-an-arl-precheck-failsl) > Step5
- [Install and boot node3](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/install_boot_node3.html) > Step 27
- [Install and boot node4](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/install_boot_node4.html) > Step 27
Thanks again for providing feedback and helping to improve the documentation,

**Comment by wdiane1** [comment]
Hi Paula,

We need to add that some more verbiage around the maxwait bootarg.

Setting this bootarg can and has caused data loss if not careful.

...Diane

**Comment by netapp-pcarriga** [comment]
@wdiane1 - Thank you for highlighting this. BURT 1518041 is tracking this issue so I'm moving your request for further updates to the BURT and we can track from there. Thanks!
