### ISSUE TITLE
Panic occurs when following procedure for FAS8300

### ISSUE THREAD

**Issue by JMnetapp** [NetAppDocs/ontap-systems-upgrade#38]
Please find the following KB with more details:

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/PANIC_%3A_rlib_port_ipspace_assign%3A_port_e0a_could_not_be_moved_to_HA_ipspace

Summary is that the documentation should be changed to reflect this caveat. When going to a platform with HA interconnects and the previous platform has those ports as client/data ports the configuration needs to be removed before the upgrade. Current the remapping of ports is done after the upgrade.

Also have Burt https://burtview.netapp.com/burts/1482496 opened for this as well.

**Comment by netapp-pcarriga** [comment]
@JMnetapp Hi Jeffrey, thank you for providing this feedback on the documentation, creating the BURT, and providing extensive details.
We'll work with the engineers to have the changes verified and then update the documentation.
Thanks!

**Comment by netapp-pcarriga** [comment]
@JMnetapp - The changes have been approved and published: [Prepare for the upgrade when moving storage (Step 5](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-prepare-when-moving-storage.html) and [Restore the root volume configuration](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-restore-root-volume-config.html)
