### ISSUE TITLE
URL for "Troubleshoot" is wrong

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems-upgrade#51]
Page: [Guidelines for upgrading controllers with ARL](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/guidelines_for_upgrading_controllers_with_arl.html)

The current (broken) URL is:
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/troubleshoot.html

It should be:
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/troubleshoot_index.html

-Andris

**Comment by netapp-pcarriga** [comment]
@andris-ntap - Thanks for highlighting this issue.  
We'll get the documentation updated as soon as possible.

**Comment by netapp-pcarriga** [comment]
@andris-ntap - The broken links have been corrected and published.
Closing his ticket. 
Thanks again!
