### ISSUE TITLE
ONTAP version update

### ISSUE THREAD

**Issue by MikePalicNTAP** [NetAppDocs/ontap-systems-upgrade#53]
Page: [Complete the upgrade in ONTAP 9.8](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-complete-ontap-9-8.html)

This set of docs seems to stop at 9.8.    Can we update to include 9.8+. (9.9.1 etc... ).

**Comment by MikePalicNTAP** [comment]
This PDF as well - https://docs.netapp.com/us-en/ontap-systems-upgrade/pdfs/sidebar/Upgrade_by_moving_volumes_or_storage.pdf

**Comment by netapp-pcarriga** [comment]
@MikePalicNTAP - Thank you for bringing this to our attention.
I'll investigate and update the documentation as soon as possible.
Thank you for helping us improve our customer documentation.

**Comment by netapp-pcarriga** [comment]
@MikePalicNTAP - We have updated the "Upgrade by moving volumes or storage" documentation to include ONTAP versions later than ONTAP 9.8.
Thank you again.
