### ISSUE TITLE
Need to add bullet to move 6-1/6-2 sub-slot blank cartridges over to new NVRAM11 module

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems-upgrade#61]
Page: [Retire node1](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/retire_node1.html)

Field feedback is showing some confusion about what to do with the blank modules that go into 6-1 and 6-2.  I'd like to add this 1st bullet in the list in this section (Stage 2) and the equivalent section in Stage 4 (for node 2).

You must install the AFF A900 or FAS9500 NVRAM and controller modules that you received for the upgrade on node1.

- Move all blank filler modules in slots 6-1 and 6-2 from the old NVRAM module to the new NVRAM module.
- Do NOT move the coredump device from the AFF A700 NVRAM module to the AFF A900 NVRAM module.
- Move all flash cache modules installed in the FAS9000 NVRAM module to the FAS9500 NVRAM module.
 
Similar addition in Stage 4.

**Comment by netapp-pcarriga** [comment]
@andris-ntap - Thanks for providing this feedback, tracking in BURT 1506458.

**Comment by netapp-pcarriga** [comment]
@andris-ntap  The updates are now published on the following pages:
[https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/retire_node1.html#install-the-aff-a900-or-fas9500-nvram-and-controller-modules-on-node1](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/retire_node1.html#install-the-aff-a900-or-fas9500-nvram-and-controller-modules-on-node1)
[Install the AFF A900 or FAS9500 NVRAM and controller modules on node2](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/install_a900_nvs_and_controller_on_node2.html)
