### ISSUE TITLE
BMC login after headswap

### ISSUE THREAD

**Issue by woutervervloesem** [NetAppDocs/ontap-systems-upgrade#63]
Page: [Perform final upgrade steps in ONTAP 9.8 or later](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-final-upgrade-steps-in-ontap-9-8.html)

We noticed during some recent headswaps that we aren't able to login to the BMC using another user than the admin account.
To be able to use another user, we need to change the password after the headswap. 

I don't know if this is expected behaviour, but it can be helpful to add this to the documentation.

**Comment by netapp-pcarriga** [comment]
@netapp-chandaj: This issue is still in progress.

**Comment by netapp-pcarriga** [comment]
Hi @netapp-chandaj - Still in progress.

**Comment by netapp-pcarriga** [comment]
HI @woutervervloesem, instructions on how re-create the non-default user accounts have been added to the upgrade by moving storage documentation. You can view this change using the following link:
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-final-upgrade-steps-in-ontap-9-8.html
Thanks again for bringing this to our attention and helping us improve the customer documentation.
