### ISSUE TITLE
can we convert this into a general how to decommission my ONTAP node?

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap-systems-upgrade#73]
Page: [Decommission the old system](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual-app/decommission_old_system.html)

instead of having repeat procedures for each head upgrade , it would be more valuable and easier to have 1 general page that you link to that covers how to decomm your system to prevent auto case creation , etc.

thank you

**Comment by netapp-pcarriga** [comment]
@loganbaez - Thank you for your feedback. We will review your suggestion and then update you here.

**Comment by netapp-pcarriga** [comment]
Hi @loganbaez - I've created BURT 1534898 to track this update. Closing this ticket. Thanks!
