### ISSUE TITLE
Update request for NSM modules - SSE Request

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap-systems-upgrade#77]
Page: [Convert an original node to a drive shelf](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-convert-node-to-shelf.html)

Since the link page - https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-considerations.html - mentions A250 as one of the controllers able to be converted.  This particular DOC is focused on IOM modules while the A250 conversion would take NSM modules and different connectivity than SAS.  Could we update this DOC to reflect this other option?

**Comment by netapp-pcarriga** [comment]
@TimMcGue Hi Tim, thanks for your recommendation. We'll review and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
Hi @TimMcGue - NetApp has recently published the upgrade procedure [[Upgrade AFF A250 to AFF A400 by converting to a drive shelf](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade_aff_a250_to_aff_a400_ndu_upgrade_workflow.html#)](url) which documents the use of  NSM modules and different connectivity than SAS. 
Please let me know if you have further questions. Thanks!

**Comment by TimMcGue** [comment]
That's fantastic - an even better solution than expected!
