### ISSUE TITLE
set-defaults

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap-systems-upgrade#78]
Page: [Install the AFF A900 or FAS9500 NVRAM and controller modules on node2](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/install_a900_nvs_and_controller_on_node2.html)

Hello doc team!

This page is similar to the node1 page here:  https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/retire_node1.html#install-the-aff-a900-or-fas9500-controller-module-on-node1

However on the node1 page it adds these two steps that I feel should be on for node2 as well:

At the LOADER> prompt of node1, set the default environment variables:

set-defaults

Save the default environment variables settings:

saveenv

**Comment by netapp-pcarriga** [comment]
Hi @TimMcGue - Thanks for your suggestion. We'll review and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
Hi @TimMcGue, Your suggestion has been verified and published:
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/install_a900_nvs_and_controller_on_node2.html
Thanks again for providing feedback and helping us improve our customer documentation.

**Comment by TimMcGue** [comment]
Well that was fast!  Thanks so much.
