### ISSUE TITLE
Need to add AFF A150, AFF C250, AFF C400, AFFC800 to docs

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems-upgrade#82]
Page: [Considerations for upgrading controller hardware](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-considerations.html)

Need to do a review of existing controller upgrade docs to add new platform models.

**Comment by netapp-pcarriga** [comment]
Thanks @andris-ntap. I'll look into getting the supported platforms updated.

**Comment by netapp-pcarriga** [comment]
List of supported systems with internal drives has been updated on the following two pages:
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-considerations.html
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-methods.html
Thanks.
