### ISSUE TITLE
Fix the "-node" in the list

### ISSUE THREAD

**Issue by tmacsevern** [NetAppDocs/ontap-systems-upgrade#87]
### Page URL

https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/prepare_nodes_for_upgrade.html

### Page title

Prepare the nodes for upgrade

### Summary

This needs to be fixed:
service-processor show -local -instance

Should be:
service-processor show -node local -instance

I would also add " -node local" to the following lines:
   network port ifgrp show
   network port reachability show -detail

Thanks

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @tmacsevern - thanks for bringing this to our attention and also for your suggestion. I'll verify and update the documentation.

**Comment by netapp-pcarriga** [comment]
Hi @tmacsevern, these command updates are now published. Thanks again for helping us improve the customer documentation.
