### ISSUE TITLE
Is "network connections listening show -vserver Cluster" relevant for all (newer) ONTAP releases?

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-systems-upgrade#93]
### Page URL

https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-map-network-ports-ontap-9-8.html

### Page title

Map network ports using ONTAP 9.8 or later

### Summary

Hi,

I was performing a controller upgrade, A220 to A400, for a customer today and ran into "an issue".
ONTAP 9.12.1P4.

In this part of the procedure, the docs have you running "network connections listening show -vserver Cluster" and you are supposed to get some output.
Well the cluster I was working on said "There are no entries matching your query."

Googling on the subject revealed an old BURT that was fixed since a long time and since many ONTAP versions.
No evidence of it ever being present in 9.12.1.

The cluster seemed to work just fine so we decided to carry on.

Now after the job I have checked some other cluster.
ONTAP 9.8P18 does provide output for the "network connections listening show -vserver Cluster" command
ONTAP 9.12.1P2 *does not* provide output.

So it seems ONTAP behaviour changed somewhere along the line but the documentation does not reflect this.

The procedure this document is for is like ONTAP brain surgery - complex and you don't want any doubts...
Getting the docs straight on what to run, what to expect for different ONTAP version is important to say the least.

I don't have a concrete proposal for what the documentation should say instead of what it currently does but there's definitely a need for improvement.

Thanks,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @estarz, I'll discuss your feedback with the SMEs and update the documentation accordingly. Thank you for helping us improve our customer documentation.

**Comment by netapp-pcarriga** [comment]
Hi @estarz, we've added a choice table to the documentation for the "network connections listening show -vserver Cluster" command depending on your ONTAP version, which you view using the following link:
[Map network ports using ONTAP 9.8 or later](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-map-network-ports-ontap-9-8.html)

Thanks again for your feedback!
