### ISSUE TITLE
New shelves - attached or not

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-systems-upgrade#94]
### Page URL

https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-attach-shelves-reassign-disks.html

### Page title

Attach storage shelves and reassign disk ownership

### Summary

Hi,

This section of the controller upgrade procedure talks about connecting the old shelves.
A previous section had you clear any new shelves from existing configuration.

From reading the docs it's not clear that you should attach the new shelves as well as the old.

Step 1 reads: "Connect the storage shelf cables from node1/node2 to node3/node4. Verify the power supply and physical connectivity of the shelves."
That makes you (me) wonder - as my end goal is one stack of shelves, 2 old and 1 new, shall I connect the new shelf now?
Because it doesn't say to connect anything new. Only the cables from the old controllers and on the old controllers only the old disk shelves were ever connected.

I did connect all old AND new shelves and it worked just fine.
But the docs should tell me.

Best Regards,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @estarz, I'll discuss your feedback with the SMEs and update the documentation accordingly. Thank you for helping us improve our customer documentation.

**Comment by netapp-pcarriga** [comment]
Hi @estarz, based on discussions with a product SME, we won't be making changes to the documentation at this time. 

NetApp does not recommend attaching new shelves for a variety of reasons, such as duplicate labels or shelf IDs, which can cause issues during the upgrade and delays with troubleshooting. 

Please let me know here in the comments section if you have further feedback and I'll reopen this issue. Thanks again!

**Comment by estarz** [comment]
Thanks @netapp-pcarriga,

I agree on the reasoning and recommendation and that is how I performed the controller upgrade.
My ask is to make it clear in the steps then to *only* connect old shelves and *not* new shelves.
Right now the docs for this step only says "shelves" so it's not 100% clear what it refers to.

--erik

**Comment by netapp-pcarriga** [comment]
Hi @estarz, apologies for the delay in responding. Thank you for your clarification. I'll update the documentation as soon as possible.

**Comment by netapp-pcarriga** [comment]
Hi @estarz, we've added a note to highlight that new shelves should not be connected during the upgrade. You can view this change using the following link: 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-attach-shelves-reassign-disks.html

Thanks again for taking time to help us improve the customer documentation.
