### ISSUE TITLE
Typo in image on page

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-systems-upgrade#99]
### Page URL

https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html

### Page title

Choose your controller hardware upgrade procedure

### Summary

"sofware"...

<img width="328" alt="Screenshot 2023-10-26 at 10 40 14" src="https://github.com/NetAppDocs/ontap-systems-upgrade/assets/2291693/0d88c527-d360-46d9-b533-e2abd80c93fa">

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @estarz, thank you for spotting this typo. I'll update the docs as soon as possible.

**Comment by netapp-pcarriga** [comment]
Thanks @estarz. We've corrected the typos.
